# Generated by Django 5.1.3 on 2024-11-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_icon.png', null=True, upload_to='', verbose_name='Avatar'),
        ),
    ]
