# Generated by Django 5.1.3 on 2025-10-17 15:39

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_icon.png', null=True, upload_to=apps.accounts.models.avatar_upload_path, verbose_name='Avatar'),
        ),
    ]
