# Generated by Django 5.1.3 on 2025-11-23 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_message_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat_room", "timestamp"], name="chat_messag_chat_ro_9355cd_idx"
            ),
        ),
    ]
