# Generated by Django 5.1.3 on 2025-11-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_message_chat_messag_chat_ro_9355cd_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="chat_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="chat.chatroom",
            ),
        ),
    ]
