# Generated by Django 5.1.3 on 2025-11-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_notification_chat_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
    ]
